### ISSUE TITLE
加到此列表如何？

### ISSUE THREAD

**Issue by nobodxbodon** [yuyan-lang/yuyan#6]
https://github.com/chai2010/china-programming-languages

**Comment by UltimatePea** [comment]
感谢推荐！

目前考虑等0.1.0beta版本开发完成后再进行添加宣传

**Comment by UltimatePea** [comment]
感谢推荐！

虽然0.1.0beta版本尚未开发完成，最近0.1.0alpha版本可行性测试已经完成，可以加入那个列表。

**Comment by UltimatePea** [comment]
已提：https://github.com/china-programming-languages/zh-lang-book/pull/42
